### ISSUE TITLE
Error: track.PitchList is null

### ISSUE THREAD

**Issue by YuzukiTsuru** [sdercolin/UtaFormatix#1]
https://github.com/sdercolin/UtaFormatix/blob/220b7b97a74ea6214001a9bba8351276e137775a/data.cs#L911

![image](https://user-images.githubusercontent.com/12003087/57568700-8e319b00-741d-11e9-9021-2525cca9f90e.png)

**Comment by sdercolin** [comment]
Is it reproducible? If so, could you please offer the used file information about the steps to reach this error?

**Comment by YuzukiTsuru** [comment]
When I run the program, import the project file, then click on the export and it is wrong, no code content is modified.

**Comment by sdercolin** [comment]
OK, I realised that PitchList is not used anywhere. I guess it was a feature that is not finished and actually not needed. I will just remove this part.

**Comment by YuzukiTsuru** [comment]
OK,Thanks

**Comment by UlyssesWu** [comment]
I may suggest you try our [fork](https://github.com/VOICeVIO/UtaFormatix/blob/4f2d3165197796d2310ccf4d02afa21c0477ab17/Model/Track.cs#L22) which already fixed many issues like this one, and [this one](https://github.com/VOICeVIO/UtaFormatix/blob/4f2d3165197796d2310ccf4d02afa21c0477ab17/data.cs#L774) ([source](https://github.com/sdercolin/UtaFormatix/blob/7bab5d9e0f633b861f79d44a1eb6078570c0dfc5/Data.cs#L812)).

**Comment by sdercolin** [comment]
@UlyssesWu Thanks for your work! (I haven't realized it until just now)
As I am going to support Vpr and refactor a lot, could you please later submit pull requests to fix known bugs like [this](https://github.com/VOICeVIO/UtaFormatix/commit/3aa594235bbb2a2870224e9386a33b0d09b8cba5), and other major issues..
