### ISSUE TITLE
Crash on Importing .VPR

### ISSUE THREAD

**Issue by vocatart** [sdercolin/UtaFormatix#6]
When importing a V5 .vpr file, UtaFormatix will crash on export to any other format.

**Comment by sdercolin** [comment]
Could you please provide one of the vpr files that cause the crash?

**Comment by vocatart** [comment]
[vpr.zip](https://github.com/sdercolin/UtaFormatix/files/4904971/vpr.zip) here is the first .vpr file i tried, though it crashes when loading any vpr.

**Comment by sdercolin** [comment]
@Danalog Here is part of the file you provided, it looks like a UST, not VPR..
```
[#VERSION]
UST Version1.2
[#SETTING]
Tempo=180.00
Tracks=1
ProjectName=Leopard.vpr
VoiceDir=*赤嶺秀吉 CATALYST VCCV
OutFile=Leopard.vpr.wav
CacheDir=Leopard.cache
Tool1=resamplers\wavtool.exe
Tool2=resamplers\TIPS.exe
Mode2=True
[#0000]
Length=300
Lyric=あ
NoteNum=50
PreUtterance=
Velocity=180
Intensity=100
```

**Comment by vocatart** [comment]
Thats really odd, to be honest i have no idea how UST data got written to that file... but i still am having issues with any other vpr file, i made a quick vpr file that just includes one note, sorry for the earlier inconvenience, i seriously do not know how that ended up happening...
[test.zip](https://github.com/sdercolin/UtaFormatix/files/4906236/test.zip)

**Comment by sdercolin** [comment]
@Danalog 
Ok, I found that the last note is ignored so that it is recognized as an empty project. But it is not crashing.
![image](https://user-images.githubusercontent.com/7665216/87216016-93b6a800-c376-11ea-9852-58f3c7ea3687.png)

I will fix this bug later but it seems unrelated to your issue.
Could you try other vpr files?
