### ISSUE TITLE
The last note is missing when transferring ust file to other files.

### ISSUE THREAD

**Issue by uselessbug** [sdercolin/UtaFormatix#7]
Just as the title . The origin ust is on the right and when transferred into vsqx (left side)  , the last note disappeared .
UtaFormatix Version : 2.1
![)P%4S(7R22 X`I0U7LL~A_7](https://user-images.githubusercontent.com/61285640/86766573-505df000-c07d-11ea-859a-4e7499124485.png)

**Comment by sdercolin** [comment]
@uselessbug 
Fixed and released. Thanks for your report!
